=== mia-platform/Sentinel/internal/config/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "output": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "stdout"
                ]
              }
            },
            "required": [
              "type"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "file"
                ]
              },
              "file": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string"
                  }
                },
                "required": [
                  "path"
                ]
              }
            },
            "required": [
              "type"
            ]
          },
          {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "webhook"
                ]
              },
              "webhook": {
                "type": "object",
                "properties": {
                  "url": {
                    "type": "string"
                  },
                  "authentication": {
                    "type": "object",
                    "properties": {
                      "secret": {
                        "$ref": "#/definitions/secret"
                      },
                      "headerName": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            },
            "required": [
              "type"
            ]
          }
        ]
      },
      "minItems": 1,
      "maxItems": 1
    },
    "monitor": {
      "type": "object",
      "properties": {
        "interval": {
          "type": "number"
        },
        "filters": {
          "type": "object",
          "properties": {
            "whitelist": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            },
            "blacklist": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            },
            "users": {
              "type": "array",
              "items": {
                "type": "string"
              },
              "minItems": 1,
              "uniqueItems": true
            }
          },
          "additionalProperties": false,
          "anyOf": [
            {
              "required": [
                "whitelist"
              ]
            },
            {
              "required": [
                "blacklist"
              ]
            },
            {
              "required": [
                "users"
              ]
            }
          ],
          "not": {
            "allOf": [
              {
                "required": [
                  "whitelist"
                ]
              },
              {
                "required": [
                  "blacklist"
                ]
              }
            ]
          }
        }
      },
      "required": [
        "interval"
      ]
    },
    "server": {
      "type": "object",
      "properties": {
        "port": {
          "type": "number"
        }
      }
    },
    "advanced": {
      "type": "object",
      "properties": {
        "debug": {
          "type": "boolean"
        },
        "omitScanning": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "output",
    "monitor",
    "server",
    "advanced"
  ],
  "definitions": {
    "secret": {
      "type": "object",
      "properties": {
        "fromEnv": {
          "type": "string"
        },
        "fromFile": {
          "type": "string"
        }
      }
    }
  }
}

=== mia-platform/Sentinel/examples/config_webhook.json
{
	"output": [
		{
			"type": "webhook",
			"webhook": {
				"url": "http://localhost:8081/vm/webhook"
			}
		}
	],
	"monitor": {
		"interval": 10,
		"filters": {
			"whitelist": [
				"go"
			],
			"users": [
				"alessandro"
			]
		}
	},
	"server": {
		"port": 8080
	},
	"advanced": {
		"debug": true,
		"omitScanning": [
			"processs.command",
			"process.user"
		]
	}
}

=== mia-platform/Sentinel/examples/config_file.json
{
	"output": [
		{
			"type": "file",
			"file": {
				"path": "./eventsFile/file.log"
			}
		}
	],
	"monitor": {
		"interval": 30,
		"filters": {
			"whitelist": [
				"go"
			],
			"users": [
				"alessandro"
			]
		}
	},
	"server": {
		"port": 8080
	},
	"advanced": {
		"debug": true,
		"omitScanning": [
			"process.command",
			"process.user"
		]
	}
}
